## ALREADY UPTODATE

- repo: gomplate
  org: hairyhenderson
  arch: amd64-slim

- repo: oras
  org: deislabs
  arch: amd64

- repo: minikube
  org: kubernetes
  arch: amd64

- repo: serve
  org: syntaqx
  arch: x86_64

- repo: dep
  org: golang
  arch: amd64

- repo: duffle
  org: deislabs
  arch: amd64

- repo: mole
  org: davrodpin
  arch: amd64

- repo: devdash
  org: Phantas0s
  arch: x86_64

- repo: kind
  org: kubernetes-sigs
  arch: amd64

- repo: jenkins-cli
  name: jcli
  org: jenkins-zh
  arch: amd64

- repo: anycable-go
  org: anycable