name: Release with goreleaser

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      -
        name: Download dependencies
        run: go mod download
      -
        name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
